In [1]:
import pandas as pd

In [2]:
df_23 = pd.read_parquet(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\processed\df_bronze_23.parquet")
df_24 = pd.read_parquet(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\processed\df_bronze_24.parquet")
df_25 = pd.read_parquet(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\processed\df_bronze_25.parquet")
df_26 = pd.read_parquet(r"C:\Users\vitor\OneDrive\Documentos\Github\VigilIA\dados\processed\df_bronze_26.parquet")

In [ ]:
columns_23 =

In [3]:
df_23.head(3)

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
0,2,A90,2023-01-01,202301,2023,32,320500,32002,9958762,2023-01-01,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023-01-01,<NA>,<NA>,<NA>
1,2,A90,2023-01-02,202301,2023,32,320460,32002,2466066,2023-01-02,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023-01-02,<NA>,<NA>,<NA>
2,2,A90,2023-01-02,202301,2023,32,320500,32002,2486016,2023-01-01,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023-01-02,<NA>,<NA>,<NA>

In [4]:
df_24.head(3)

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
0,2,A90,2024-03-04,202410,2024,32,320150,32001,2446294,2024-03-02,...,0,0,0,0,0,0,2023-03-24,0,0,0
1,2,A90,2024-04-17,202416,2024,32,320465,32001,2445638,2024-04-15,...,0,0,0,0,0,0,2023-03-29,0,0,0
2,2,A90,2024-06-22,202425,2024,32,320520,32002,2358298,2024-06-11,...,0,0,0,0,0,0,2023-06-22,0,0,0

In [5]:
df_25.head(3)

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
0,2,A90,2025-08-26,202535,2025,26,260290,1497,19,2025-08-24,...,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,2025-11-13,1,<NA>,<NA>
1,2,A90,2025-08-27,202535,2025,26,260290,1497,19,2025-08-24,...,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,2025-11-13,1,<NA>,<NA>
2,2,A90,2025-08-26,202535,2025,26,260290,1497,19,2025-08-24,...,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,2025-11-13,1,<NA>,<NA>

In [6]:
df_26.head(3)

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
0,2,A90,2026-02-25,202608,2026,35,353440,1335,8087.0,2026-02-10,...,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,2026-02-25,0,<NA>,<NA>
1,2,A90,2026-02-25,202608,2026,35,353440,1335,8087.0,2026-02-13,...,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,2026-02-25,0,<NA>,<NA>
2,2,A90,2026-02-14,202606,2026,35,353440,1335,8087.0,2026-02-11,...,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,2026-02-25,0,<NA>,<NA>